name: flutterdoc_but_nyxx
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  http: ^1.0.0
  logging: ^1.2.0
  nyxx: ^6.0.0-dev.0
  fuzzy: ^0.4.0-nullsafety.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
